# General Jekyll Config
# url: "https://ottondrumm.github.io/"
title: Blue Sun Stories
description: Raccolta di racconti, storie ed esperienze vissute sotto il Sole Blu
show_downloads: false
github:
  show_repository_url: false

# Build settings
theme: jekyll-theme-midnight
