# This is a basic workflow to help you get started with Actions

name: ColorServerStart

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  start_color_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Grant permissions
        run: chmod +x ./godot_server/linux/Server
        
      - name: Run a one-line script
        run: sudo ./godot_server/linux/Server --no-window
